
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Font;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;

/*
 * To change this template, choose Tools | Templates and open the template in
 * the editor.
 */
/**
 *
 * @author Valeria
 */
public class GamePanel extends javax.swing.JPanel {

    private SortingGameUI sortingGameUI;

    /**
     * Creates new form BoardPanel
     */
    public GamePanel(SortingGameUI sortingGameUI) {
        this.sortingGameUI = sortingGameUI;
        initComponents();
        initBoardPanel();
        drawTilePanels();
        showMoveCount();
        initSecretCheatingPanel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        moveCountLabel = new javax.swing.JLabel();
        startNewGameButton = new javax.swing.JButton();
        statsButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();
        boardPanel = new javax.swing.JPanel();
        secretCheatingPanel = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(500, 375));

        jLabel1.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jLabel1.setText("Move count:");

        moveCountLabel.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        moveCountLabel.setText("0");

        startNewGameButton.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        startNewGameButton.setText("Start new game");
        startNewGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startNewGameButtonActionPerformed(evt);
            }
        });

        statsButton.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        statsButton.setText("Your stats");
        statsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statsButtonActionPerformed(evt);
            }
        });

        closeButton.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        boardPanel.setLayout(new java.awt.GridLayout());

        javax.swing.GroupLayout secretCheatingPanelLayout = new javax.swing.GroupLayout(secretCheatingPanel);
        secretCheatingPanel.setLayout(secretCheatingPanelLayout);
        secretCheatingPanelLayout.setHorizontalGroup(
            secretCheatingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 49, Short.MAX_VALUE)
        );
        secretCheatingPanelLayout.setVerticalGroup(
            secretCheatingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(startNewGameButton)
                        .addGap(18, 18, 18)
                        .addComponent(statsButton)
                        .addGap(18, 18, 18)
                        .addComponent(closeButton)
                        .addGap(0, 100, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(boardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(moveCountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(26, 26, 26)))
                            .addComponent(secretCheatingPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(secretCheatingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(moveCountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(boardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statsButton)
                    .addComponent(startNewGameButton)
                    .addComponent(closeButton))
                .addGap(41, 41, 41))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void initBoardPanel() {
        GridLayout boardLayout = (GridLayout) boardPanel.getLayout();
        boardLayout.setRows(sortingGameUI.getBoardRows());
        boardLayout.setColumns(sortingGameUI.getBoardColumns());
    }

    private void drawTilePanels() {
        boardPanel.removeAll();
        Tile[][] boardTiles = sortingGameUI.getBoardTiles();
        for (int row = 0; row < boardTiles.length; row++) {
            for (int column = 0; column < boardTiles[row].length; column++) {
                Tile tile = boardTiles[row][column];
                if (tile != null) {
                    boardPanel.add(initTilePanel(row, column, tile));
                } else {
                    boardPanel.add(new JPanel());
                }
            }
            boardPanel.revalidate();
        }
    }

    private JPanel initTilePanel(final int row, final int column, Tile tile) {
        JPanel tilePanel = new JPanel();
        tilePanel.setBackground(new Color(0, 102, 102));
        tilePanel.setBorder(BorderFactory.createLineBorder(Color.lightGray));
        if (tile != null) {
            JLabel orderNumber = new JLabel("" + tile.getOrderNumber());
            orderNumber.setFont(new Font("Segoe UI Symbol", Font.BOLD, 18));
            orderNumber.setForeground(Color.lightGray);
            tilePanel.add(orderNumber);
            tilePanel.addMouseListener(new MouseAdapter() {

                @Override
                public void mouseClicked(MouseEvent me) {
                    sortingGameUI.moveTile(row, column);
                    drawTilePanels();
                    showMoveCount();
                    sortingGameUI.checkIfTilesInOrder();
                }
            });
        }
        return tilePanel;
    }

    private void showMoveCount() {
        moveCountLabel.setText("" + sortingGameUI.getMoveCount());
    }

    private void initSecretCheatingPanel() {
        secretCheatingPanel.addMouseListener(new MouseAdapter() {

            @Override
            public void mouseClicked(MouseEvent me) {
                sortingGameUI.cheat();
                drawTilePanels();
                showMoveCount();
            }
        });
    }

    private void startNewGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startNewGameButtonActionPerformed
        sortingGameUI.deleteSavedGame();
        sortingGameUI.addGameStats();
        sortingGameUI.showBoardSettingPanel();
    }//GEN-LAST:event_startNewGameButtonActionPerformed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        sortingGameUI.closeGame();
    }//GEN-LAST:event_closeButtonActionPerformed

    private void statsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statsButtonActionPerformed
        sortingGameUI.showStats();
    }//GEN-LAST:event_statsButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel boardPanel;
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel moveCountLabel;
    private javax.swing.JPanel secretCheatingPanel;
    private javax.swing.JButton startNewGameButton;
    private javax.swing.JButton statsButton;
    // End of variables declaration//GEN-END:variables
}
